version: '3.4'

services:
  app:
    image: node:alpine
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: dev
    command: sh -c "npm install;npm run dev"

  tests:
    image: node:alpine
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      NODE_ENV: test
